unit nextpas.core.platform.windows.base;

{$I nextpas.core.settings.inc}

interface

type
  BYTE = UInt8;
  WORD = UInt16;
  UINT = UInt32;
  DWORD = UInt32;
  WINBOOL = LongBool;
  BOOL = WINBOOL;
  HANDLE = Pointer;
  FARPROC = Pointer;
  HMODULE = HANDLE;
  LPVOID = Pointer;
  LPCSTR = PAnsiChar;
  LPSTR = PAnsiChar;
  LPCWSTR = PWideChar;
  LPWSTR = PWideChar;
  LPDWORD = ^DWORD;
  LPBYTE = ^BYTE;
  PLPSTR = ^LPSTR;
  PLPWSTR = ^LPWSTR;
  SRWLOCK = Pointer;
  CONDITION_VARIABLE = Pointer;
  TPlatformWindowsThreadProc = function(AArg: Pointer): Pointer; cdecl;

  FILETIME = record
    dwLowDateTime: DWORD;
    dwHighDateTime: DWORD;
  end;

  GET_FILEEX_INFO_LEVELS = (
    GetFileExInfoStandard,
    GetFileExMaxInfoLevel
  );
  PGET_FILEEX_INFO_LEVELS = ^GET_FILEEX_INFO_LEVELS;

  WIN32_FILE_ATTRIBUTE_DATA = packed record
    dwFileAttributes: DWORD;
    ftCreationTime: FILETIME;
    ftLastAccessTime: FILETIME;
    ftLastWriteTime: FILETIME;
    nFileSizeHigh: DWORD;
    nFileSizeLow: DWORD;
  end;
  PWIN32_FILE_ATTRIBUTE_DATA = ^WIN32_FILE_ATTRIBUTE_DATA;

  BY_HANDLE_FILE_INFORMATION = record
    dwFileAttributes: DWORD;
    ftCreationTime: FILETIME;
    ftLastAccessTime: FILETIME;
    ftLastWriteTime: FILETIME;
    dwVolumeSerialNumber: DWORD;
    nFileSizeHigh: DWORD;
    nFileSizeLow: DWORD;
    nNumberOfLinks: DWORD;
    nFileIndexHigh: DWORD;
    nFileIndexLow: DWORD;
  end;
  PBY_HANDLE_FILE_INFORMATION = ^BY_HANDLE_FILE_INFORMATION;

  SECURITY_ATTRIBUTES = record
    nLength: DWORD;
    lpSecurityDescriptor: LPVOID;
    bInheritHandle: WINBOOL;
  end;
  LPSECURITY_ATTRIBUTES = ^SECURITY_ATTRIBUTES;

  PROCESS_INFORMATION = record
    hProcess: HANDLE;
    hThread: HANDLE;
    dwProcessId: DWORD;
    dwThreadId: DWORD;
  end;
  LPPROCESS_INFORMATION = ^PROCESS_INFORMATION;

  STARTUPINFOA = record
    cb: DWORD;
    lpReserved: LPSTR;
    lpDesktop: LPSTR;
    lpTitle: LPSTR;
    dwX: DWORD;
    dwY: DWORD;
    dwXSize: DWORD;
    dwYSize: DWORD;
    dwXCountChars: DWORD;
    dwYCountChars: DWORD;
    dwFillAttribute: DWORD;
    dwFlags: DWORD;
    wShowWindow: WORD;
    cbReserved2: WORD;
    lpReserved2: LPBYTE;
    hStdInput: HANDLE;
    hStdOutput: HANDLE;
    hStdError: HANDLE;
  end;
  LPSTARTUPINFOA = ^STARTUPINFOA;

  STARTUPINFOW = record
    cb: DWORD;
    lpReserved: LPWSTR;
    lpDesktop: LPWSTR;
    lpTitle: LPWSTR;
    dwX: DWORD;
    dwY: DWORD;
    dwXSize: DWORD;
    dwYSize: DWORD;
    dwXCountChars: DWORD;
    dwYCountChars: DWORD;
    dwFillAttribute: DWORD;
    dwFlags: DWORD;
    wShowWindow: WORD;
    cbReserved2: WORD;
    lpReserved2: LPBYTE;
    hStdInput: HANDLE;
    hStdOutput: HANDLE;
    hStdError: HANDLE;
  end;
  LPSTARTUPINFOW = ^STARTUPINFOW;

  SYSTEM_INFO = record
    dwOemId: DWORD;
    dwPageSize: DWORD;
    lpMinimumApplicationAddress: Pointer;
    lpMaximumApplicationAddress: Pointer;
    dwActiveProcessorMask: PtrUInt;
    dwNumberOfProcessors: DWORD;
    dwProcessorType: DWORD;
    dwAllocationGranularity: DWORD;
    wProcessorLevel: UInt16;
    wProcessorRevision: UInt16;
  end;

  TWinThreadStartRoutine = function(lpThreadParameter: Pointer): DWORD; stdcall;
  PPlatformWindowsThreadState = ^TPlatformWindowsThreadState;
  TPlatformWindowsThreadState = record
    Handle: HANDLE;
    Proc: TPlatformWindowsThreadProc;
    Arg: Pointer;
    ReturnValue: Pointer;
    RefCount: Int32;
  end;

  TPlatformWindowsMutexAlign = record
    Value: SRWLOCK;
  end;

  TPlatformWindowsRwLockAlign = record
    Value: SRWLOCK;
  end;

  TPlatformWindowsCondVarAlign = record
    Value: CONDITION_VARIABLE;
  end;

const
  INFINITE = DWORD($FFFFFFFF);
  WAIT_OBJECT_0 = DWORD(0);
  WAIT_ABANDONED_0 = DWORD($80);
  WAIT_TIMEOUT = DWORD($102);
  WAIT_IO_COMPLETION = DWORD($C0);
  WAIT_ABANDONED = DWORD($80);
  WAIT_FAILED = DWORD($FFFFFFFF);
  STILL_ACTIVE = DWORD($103);
  ERROR_TIMEOUT = DWORD(1460);
  TLS_OUT_OF_INDEXES = DWORD($FFFFFFFF);
  DUPLICATE_CLOSE_SOURCE = DWORD(1);
  DUPLICATE_SAME_ACCESS = DWORD(2);
  SYNCHRONIZE = DWORD($100000);
  PROCESS_TERMINATE = DWORD($0001);
  PLATFORM_WINDOWS_INVALID_HANDLE_VALUE = PtrInt(-1);
  PLATFORM_WINDOWS_MEM_COMMIT = DWORD($00001000);
  PLATFORM_WINDOWS_MEM_RESERVE = DWORD($00002000);
  PLATFORM_WINDOWS_MEM_DECOMMIT = DWORD($00004000);
  PLATFORM_WINDOWS_MEM_RELEASE = DWORD($00008000);
  PLATFORM_WINDOWS_PAGE_NOACCESS = DWORD($00000001);
  PLATFORM_WINDOWS_PAGE_READONLY = DWORD($00000002);
  PLATFORM_WINDOWS_PAGE_READWRITE = DWORD($00000004);
  PLATFORM_WINDOWS_PAGE_EXECUTE_READ = DWORD($00000020);
  PLATFORM_WINDOWS_PAGE_EXECUTE_READWRITE = DWORD($00000040);
  PLATFORM_WINDOWS_GENERIC_READ = DWORD($80000000);
  PLATFORM_WINDOWS_GENERIC_WRITE = DWORD($40000000);
  PLATFORM_WINDOWS_FILE_SHARE_READ = DWORD(1);
  PLATFORM_WINDOWS_FILE_SHARE_WRITE = DWORD(2);
  PLATFORM_WINDOWS_FILE_SHARE_DELETE = DWORD(4);
  PLATFORM_WINDOWS_CREATE_ALWAYS = DWORD(2);
  PLATFORM_WINDOWS_OPEN_EXISTING = DWORD(3);
  PLATFORM_WINDOWS_OPEN_ALWAYS = DWORD(4);
  PLATFORM_WINDOWS_TRUNCATE_EXISTING = DWORD(5);
  PLATFORM_WINDOWS_DEBUG_PROCESS = DWORD(1);
  PLATFORM_WINDOWS_DEBUG_ONLY_THIS_PROCESS = DWORD(2);
  PLATFORM_WINDOWS_CREATE_SUSPENDED = DWORD(4);
  PLATFORM_WINDOWS_DETACHED_PROCESS = DWORD(8);
  PLATFORM_WINDOWS_CREATE_NEW_CONSOLE = DWORD(16);
  PLATFORM_WINDOWS_NORMAL_PRIORITY_CLASS = DWORD(32);
  PLATFORM_WINDOWS_IDLE_PRIORITY_CLASS = DWORD(64);
  PLATFORM_WINDOWS_HIGH_PRIORITY_CLASS = DWORD(128);
  PLATFORM_WINDOWS_REALTIME_PRIORITY_CLASS = DWORD(256);
  PLATFORM_WINDOWS_CREATE_NEW_PROCESS_GROUP = DWORD(512);
  PLATFORM_WINDOWS_CREATE_UNICODE_ENVIRONMENT = DWORD($00000400);
  PLATFORM_WINDOWS_CREATE_SEPARATE_WOW_VDM = DWORD($00000800);
  PLATFORM_WINDOWS_CREATE_SHARED_WOW_VDM = DWORD($00001000);
  PLATFORM_WINDOWS_CREATE_FORCEDOS = DWORD($00002000);
  PLATFORM_WINDOWS_BELOW_NORMAL_PRIORITY_CLASS = DWORD($00004000);
  PLATFORM_WINDOWS_ABOVE_NORMAL_PRIORITY_CLASS = DWORD($00008000);
  PLATFORM_WINDOWS_STACK_SIZE_PARAM_IS_A_RESERVATION = DWORD($00010000);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_READONLY = DWORD($00000001);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_HIDDEN = DWORD($00000002);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_SYSTEM = DWORD($00000004);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_DIRECTORY = DWORD($00000010);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_ARCHIVE = DWORD($00000020);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_DEVICE = DWORD($00000040);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_NORMAL = DWORD($80);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_TEMPORARY = DWORD($00000100);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_SPARSE_FILE = DWORD($00000200);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_REPARSE_POINT = DWORD($00000400);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_COMPRESSED = DWORD($00000800);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_OFFLINE = DWORD($00001000);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_NOT_CONTENT_INDEXED = DWORD($00002000);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_ENCRYPTED = DWORD($00004000);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_INTEGRITY_STREAM = DWORD($00008000);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_VIRTUAL = DWORD($00010000);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_NO_SCRUB_DATA = DWORD($00020000);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_EA = DWORD($00040000);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_PINNED = DWORD($00080000);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_UNPINNED = DWORD($00100000);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_RECALL_ON_OPEN = DWORD($00040000);
  PLATFORM_WINDOWS_FILE_ATTRIBUTE_RECALL_ON_DATA_ACCESS = DWORD($00400000);
  WINDOWS_FILETIME_UNIX_EPOCH_OFFSET_100NS = UInt64(116444736000000000);
  WINDOWS_FILETIME_NANOSECONDS_PER_TICK = UInt64(100);
  PLATFORM_WINDOWS_MUTEX_SIZE = SizeOf(SRWLOCK);
  PLATFORM_WINDOWS_RWLOCK_SIZE = SizeOf(SRWLOCK);
  PLATFORM_WINDOWS_CONDVAR_SIZE = SizeOf(CONDITION_VARIABLE);

implementation

end.
